// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product_Management.Data;

#nullable disable

namespace Product_Management.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20260310145710_RenameTable")]
    partial class RenameTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product_Management.Entity_Models.ProductEntityModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CASE When StockQuantity > 0 THEN 1 ELSE 0 END", true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Electronics",
                            IsActive = true,
                            Price = 599.5m,
                            ProductName = "Wireless mouse",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Electronics",
                            IsActive = true,
                            Price = 899.0m,
                            ProductName = "USB Charger",
                            StockQuantity = 7
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Wearable",
                            IsActive = true,
                            Price = 999m,
                            ProductName = "SmartWatch",
                            StockQuantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Home & Office",
                            IsActive = true,
                            Price = 1499.25m,
                            ProductName = "Work table",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Home & Office",
                            IsActive = false,
                            Price = 99m,
                            ProductName = "Desk lamp",
                            StockQuantity = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
